### PR TITLE
Added Marek to collaborators

### PR DESCRIPTION
**Pull request by renra**

### CODE REVIEW

**Comment by turboMaCk** [comment]
Seems like there is issue in "deploy" step on circle. BTW don't you want to add badge to README.md as well.

**Comment by renra** [comment]
That's because I'm a syntax-error making fool, especially when I try to multitask. Fixed now, badge is there too.

**Comment by renra** [comment]
**RDY**

**Comment by turboMaCk** [comment]
Nice one. Probably you want to remove v2.0.0 release and create it again.

**Pull request merged**
